---
title: "Delta Pangenome Exploration"
output: html_document
date: '2022-12-27'
---

```{bash delta, eval=FALSE}
codelib=/home/jbonnie1/dandd/dev-dandD/lib
datadir=/data/blangme2/fasta/hprc-yr1
jdatadir=/data/blangme2/jessica/pangenome
hgwkdir=/scratch4/blangme2/jessica/dandd/scratch/HGSVC2
wkdir=/scratch4/blangme2/jessica/dandd/scratch/pangenome
fasta_list=${jdatadir}/pangenome_fasta_paths.txt
female_fastas=${jdatadir}/pangenome_fasta_paths_female.txt
overlap_list=${wkdir}/pangenome_hgsvc2_fasta_paths.txt
foverlap_list=${wkdir}/pangenome_hgsvc2_fasta_paths_female.txt
hgoverlap_list=${hgwkdir}/pangenome_hgsvc2_fasta_paths.txt
hgoverlap_female=${hgwkdir}/pangenome_hgsvc2_fasta_paths_female.txt
hgfemale_fastas=/data/blangme2/jessica/HGSVC2/consensus_fastas_nonrel_female.txt
realpath ${datadir}/HG*.fa > ${fasta_list}
realpath ${datadir}/NA*.fa >> ${fasta_list}


## FEMALES SUBSETTING HERE
awk '{print $1}' ${jdatadir}/hprc_year1_assemblies_v2_sample_metadata.txt > ${jdatadir}/hprc_year1_SampleIds.txt
grep female ${jdatadir}/hprc_year1_assemblies_v2_sample_metadata.txt | awk '{print $1}' > ${jdatadir}/hprc_year1_females.txt
grep -f ${jdatadir}/hprc_year1_females.txt ${fasta_list} > ${female_fastas}

## create overlap list with HGSVC2 all sexes ... turns out several of these people are from the related list??
grep -f /data/blangme2/jessica/HGSVC2/raw/SampleIds.txt ${fasta_list} > ${overlap_list}
grep -f /data/blangme2/jessica/HGSVC2/raw/SampleIds_female.txt ${female_fastas} > ${foverlap_list}


## Create overlap list in the HGSVC2 data

awk '{print $0"_"}' ${jdatadir}/hprc_year1_SampleIds.txt | grep -f /dev/stdin /data/blangme2/jessica/HGSVC2/consensus_fastas.txt > ${hgoverlap_list}
awk '{print $0"_"}' ${jdatadir}/hprc_year1_females.txt | grep -f /dev/stdin /data/blangme2/jessica/HGSVC2/consensus_fastas.txt > ${hgoverlap_female}


## Run full pangenome: make a tree and do progressive union on that tree... maybe do a ksweep if that feels right
python ${codelib}/dandd_cmd.py tree -s female -f ${female_fastas} -k20 -o ${wkdir}
tree_pick=${wkdir}/female_56_dashing_dtree.pickle
python ${codelib}/dandd_cmd.py progressive -d ${tree_pick} -n 30
python ${codelib}/dandd_cmd.py info -d ${tree_pick} -o ${wkdirdir}/${tag}_ksweep_dashing.csv --mink 10 --maxk 30
python ${codelib}/dandd_cmd.py progressive -d ${tree_pick} -n 90
#tree_pick=${outdir}/female_progu30_56_dashing_dtree.pickle
#python ${codelib}/dandd_cmd.py info -d ${tree_pick} -o ${outdir}/${tag}_ksweep_dashing.csv --mink 18 --maxk 30


## Run 8 overlapping samples in pangenome set
python ${codelib}/dandd_cmd.py tree -s overlap -f ${overlap_list} -k18 -o ${wkdir}
dtree=${wkdir}/overlap_8_dashing_dtree.pickle

python ${codelib}/dandd_cmd.py progressive -d ${dtree} -f ${overlap_list} -n 90 #-r ${orderings}
#Use same orderings when working on subset in HGSVC2 data
orderings=${wkdir}/sketchdb/overlap_8_orderings.pickle

## Overlapping HGSVC2 Samples
cd ${hgwkdir}
python ${codelib}/dandd_cmd.py tree -s overlap -f ${hgoverlap_list} -k18 -o ${hgwkdir}
tree_pick=${hgwkdir}/overlap_8_dashing_dtree.pickle
python ${codelib}/dandd_cmd.py progressive -d ${tree_pick} -r ${orderings}

cp /scratch4/blangme2/jessica/dandd/scratch/HGSVC2/overlap_progu0_8_dashing.csv /scratch4/blangme2/jessica/dandd/scratch/HGSVC2/hgoverlap_progu90_8_dashing.csv
```

```{r prep, echo=FALSE,warning=FALSE, include=FALSE}

require(tidyr)
require(ggplot2)
require(dplyr)
require(data.table)
require(openssl)
require(dplyr)
require(optparse)
require(callr)
require(codetools)
codelib<-'/home/jbonnie1/dandd/dev-dandD/lib/'
source(file.path(codelib,'plot_progressive.R'))

outdir<-'/scratch4/blangme2/jessica/dandd/scratch/pangenome'

```


```{r females}
tag='pangenome'
females<-read.csv('/scratch4/blangme2/jessica/dandd/scratch/pangenome/female_progu30_56_dashing.csv') %>% mutate(dataset="Pangenome") %>% select(-fastas)
write.csv(x=females,"../figures/pangenome/female_progu30_56_dashing.csv", row.names = FALSE)
plotCumulativeUnion(progu=females, title="56 Female Pangenome Haplotypes, 30 orderings", nshow=5)


```


## 8 Female overlapping samples (include related individuals)



```{r pressure, echo=FALSE}
tag='overlap'

overlap<-read.csv('/scratch4/blangme2/jessica/dandd/scratch/pangenome/overlap_progu90_8_dashing.csv') %>% 
  mutate(dataset="Pangenome")
plotCumulativeUnion(progu=overlap,title = "90 Orderings of 8 Samples", nshow=0)

hgsvc2<-read.csv('/scratch4/blangme2/jessica/dandd/scratch/HGSVC2/hgoverlap_progu90_8_dashing.csv') %>% 
  mutate( dataset="HGSVC2")
progu=rbind(overlap,hgsvc2) 
summary <- progu %>% group_by(ngen) %>% summarize(mean=mean(delta),sd=sd(delta))

plotCumulativeUnion(progu=progu,title="8 Overlapping Female Samples", nshow=0)

```


```{r plot_across, cache=TRUE}
norder=max(overlap$ordering)
gcount=max(overlap$ngen)
summary <- 
allg <-

  ggplot() +
  geom_smooth(data = overlap, aes(y=delta, x=ngen, color="pangenome"), method='loess',formula=y~x,se=TRUE) +
  geom_smooth(data = hgsvc2, aes(y=delta, x=ngen, color="HGSVC2"), method='loess',formula=y~x, se=TRUE) +


  #geom_point(data=function(x) subset(x,Indicator),aes(y=delta_pos, x=ngenomes, shape=kval), size=2) +
  # scale_linetype_manual(name=paste0("Fit (",norder," Orderings)"),values=c(2)) +
  # geom_line(data=function(x) subset(x,Indicator),aes(y=delta_pos, x=ngenomes, group=ordering,color=as.factor(ordering)), size=.5) +
  theme_bw() +
  scale_x_continuous(breaks= scales::pretty_breaks(10)) +
  # scale_shape_discrete(name="argmax(k)")+
  # scale_color_discrete(name = "Random Genome Ordering") +
  xlab("Number of Genomes in Set") +
  ylab("Value of \u03b4") +
  ggtitle(label=paste0("Values of \u03b4 over ",norder," orderings of ",gcount," Overlapping HGSVC2 and Pangenomes")) 
#+xlim(c(1,3))
  # guides(color = "none")

allg
```





### Graveyard




```{bash hgsvc2, eval=FALSE}
filelist=/scratch16/blangme2/jessica/data/HGSVC2/consensus_pangenome_overlap.txt
grep -E "(_HG00733|_HG02818|_HG03486|_NA19240)" /home/jbonnie1/scr16_blangme2/jessica/data/HGSVC2/consensus_fastas.txt > ${filelist}

python ${codelib}/dandd_cmd.py tree -s hgsvc2_overlap -f ${filelist} --nthreads 20 -k19

dtree=/scratch16/blangme2/jessica/dandd/scratch/HGSVC2/hgsvc2_overlap_8_dashing_dtree.pickle
orderings=/scratch16/blangme2/jessica/dandd/scratch/pangenome/sketchdb/overlap_8_orderings.pickle
python ${codelib}/dandd_cmd.py progressive -d ${dtree} -f ${filelist} -r ${orderings}

python ${codelib}/dandd_cmd.py kij -d ${dtree} --mink 10 --maxk 30

```

